### ISSUE TITLE
replace peer records with signed peer records in Add/GetProviders messaging

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-libp2p-dht#1]

**Comment by cskiraly** [comment]
Currently Add/Get providers sends simple PeerRecords. We should change this, probably in two steps.

1, send signed PeerRecords, and on the receiver side verify that the sender and actual record matches.
2, send signed envelopes also binding to the CID for which the provider is registered. This would mean a signed envelope that contains both the PeerRecord and the CID.

Eventually we might introduce other data structures, such as a list of CID signed in an Envelope, coupled with a signed PeerRecord. This could improve efficiency, batching providers information.

**Comment by emizzle** [comment]
Libp2p PR open that defines signed peer records: https://github.com/status-im/nim-libp2p/pull/647

**Comment by emizzle** [comment]
Validation of peer record on the receiving of a `AddProvider`:
1. validate the signed peer record
2. validate that the distance is reasonable compared to self id

**Comment by emizzle** [comment]
Currently, if we use signed peer records only, we can only validate the source's PeerID and not the CID that a provider is being added for. This is where we might need to use an envelope to also include the CID in the message that can be validated for distance (see comment above).

**Comment by emizzle** [comment]
How do we determine the distance threshold?

**Comment by cskiraly** [comment]
Current specs version we are looking at is https://github.com/libp2p/specs/tree/65f9923a405a8b33c4208a3d8b9e6340b9474efc/kad-dht#rpc-messages

**Comment by cskiraly** [comment]
Verification on reception of response to GetProviders: this should ideally be done based on the CID, but that is not yet there. Maybe we need an Envelope[(PeerRecord,CID)].
This could even have multiple CIDs in it, only requiring one to be close to the actual node where it is being stored.
