### ISSUE TITLE
Use libp2p crypto instead of nim-eth/keys

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-libp2p-dht#2]
Use libp2p crypto instead of all other cryptos (eth/keys, nimcrypto, etc).

In libp2p, can be secp256k1 or a few others. We are only going to use secp256k1.

**Comment by cskiraly** [comment]
We are currently using a mix of two crypto imports:
- eth/keys
- libp2p/libp2p/crypto
Both are based on underlying nimcrypto and secp256k1 libraries, but use `distinct` types to redefine Private/Public keys.
Ideally, we should only use one of the two to simplify the code.

**Comment by Menduist** [comment]
@cskiraly took the first card, LMK if you want me to do something else

**Comment by emizzle** [comment]
@emizzle ive got an open branch with the majority of this work already done.

**Comment by emizzle** [comment]
I see there's a draft pr #31 for this work, hopefully some of the work I did the branch above can help get this across the line.
