### ISSUE TITLE
replace ENRs with libp2p signed peer records

### ISSUE THREAD

**Issue by cskiraly** [status-im/nim-libp2p-dht#4]
The base code uses ENRs and their binary wire encoding to exchange signed peer records with network address, public keys, and peer IDs. We have a similar structure in libp2p, the signed PeerRecord, which is a Peer Record in an envelope.

We should remove the use of ENRs and use the libp2p native structure instead.

Initial implementation in https://github.com/status-im/nim-libp2p-dht/tree/libp2p-peerrecord

**Comment by emizzle** [comment]
Closed by #28.
